
---
include:
  - board: nrf52840_mdk_dongle
    shield: dongle
  - board: nrf52840_mdk_dongle
    shield: settings_reset
  - board: xiao_ble
    shield: dongle
  - board: xiao_ble
    shield: settings_reset
  - board: nrf52840dongle_nrf52840
    shield: reset_button
  - board: nice_nano_v2
    shield: dongle
  - board: nice_nano_v2
    shield: settings_reset
